### ISSUE TITLE
Onset!

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework2G1#1]
So which matrix operation are you going  to implement guys?

**Comment by JustinJaniszewski** [comment]
how does matrix multiplication and dot product sound to you guys?

**Comment by uarif** [comment]
I guess we should go with matrix multiplication and dot product @JustinJaniszewski @tirthbha

**Comment by JustinJaniszewski** [comment]
it is decided Matrix multiplication and dot product then.
