### ISSUE TITLE
Matrix shape?

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework2G1#20]
Which shape of matrix you guys have chosen?
@JustinJaniszewski 
@uarif

**Comment by JustinJaniszewski** [comment]
Mmm, im not sure what you mean but I think that should be up to @uarif as he in charge of the algorithm

**Comment by uarif** [comment]
> Which shape of matrix you guys have chosen? @JustinJaniszewski @uarif

3*3
