### ISSUE TITLE
Does anyone know how to edit a milestone?

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework2G1#21]
I was going to add all of our issues discussing getting started (like assigning tasks and maintainer, etc.) to the milestone created. However, the milestone name isn't very descriptive. Is there a way to edit it or should I add a new milestone?

**Comment by JustinJaniszewski** [comment]
I'll just create a new one for the time being but I will leave this open in case someone is able to answer this to prevent this problem in the future.

**Comment by JustinJaniszewski** [comment]
Actually, I am unable to create one. @uarif Are you able to edit the milestone? If not could you let me know how to create one?

**Comment by AhmedCode99** [comment]
Yes

Go to issues > Milestones > Add New MileStone
