### ISSUE TITLE
Pull request issue

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework2G1#22]
@uarif in your pull request (#16) you ask someone to accept your merge request however you are the only one able to accept merge requests. You can just accept your own request.

**Comment by uarif** [comment]
> @uarif in your pull request (#16) you ask someone to accept your merge request however you are the only one able to accept merge requests. You can just accept your own request.

Actually, you were right. I meant to request Dr. Tim. IDK why did I request myself. Thank you

**Comment by JustinJaniszewski** [comment]
No problem.
