### ISSUE TITLE
Adding a Plot

### ISSUE THREAD

**Issue by AhmedCode99** [ubsuny/23-Homework2G1#25]
Your code ran well, but the output was not looking nice. So I added a code to plot your results. Which is a much nicer way to present your results.

**Comment by Mosaddeq107** [comment]
It is not mandatory to add a chart, but it is the best way to show our work graphically. So, we added this as well.

**Comment by uarif** [comment]
Yes you're correct. 👍

**Comment by AhmedCode99** [comment]
Great!
