### ISSUE TITLE
Docstring

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework2G1#27]
We need to add docstring to the code.

**Comment by Mosaddeq107** [comment]
What is the process of adding docstring to the code?

**Comment by tirthbha** [comment]
> What is the process of adding docstring to the code?

Simply including  docstrings in your code  provides clear and concise documentation. For example, in function docstring, you can do like: place a triple-quoted string immediately below the function definition. Inside the triple-quotes, describe the function, its arguments, and return values (if any).
