### ISSUE TITLE
Dot_product_code

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework2G1#32]
Hi, The code is there, it's not refined, but you can start writing about it.. @tirthbha

**Comment by tirthbha** [comment]
Have you checked that code for its correctness? @uarif

**Comment by uarif** [comment]
> Have you checked that code for its correctness? @uarif

Of course, I have. Why it doesn't work with you?

**Comment by uarif** [comment]
> Have you checked that code for its correctness? @uarif
These are the results..
Dot Product using np.sum: 49093067
Execution time using np.sum: 0.0023679733276367188 seconds
Dot Product using a loop: 49093067
Execution time using a loop: 0.00010848045349121094 seconds
Dot Product using np.einsum: 49093067
Execution time using np.einsum: 0.00014519691467285156 seconds
Dot Product using np.einsum: 49093067
Execution time using np.einsum: 0.00016832351684570312 seconds

**Comment by tirthbha** [comment]
Yeah! I have don. It's fine. I have added this one to the documentation.md file
________________________________
