### ISSUE TITLE
Conversation...

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework2G1#35]
We have points for conversations, please create them. Thank you, 
@tirthbha @JustinJaniszewski

**Comment by tirthbha** [comment]
As we are aware that tomorrow is the last deadline. What changes are required to the documentation file? Do we need to add more there or not?

**Comment by uarif** [comment]
> As we are aware that tomorrow is the last deadline. What changes are required to the documentation file? Do we need to add more there or not?

Just follow the rules for writing documentation, you should be fine.
