### ISSUE TITLE
References in Documentation.

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework2G1#37]
Hy, so while writing documemtation, where are we supposed to place the references? Should we place it at last or should we put it in the the exact place where it is used? @tirthbha any idea?

**Comment by uarif** [comment]
At the end would be fine, I guess. You can even put your references like the usual document, [1] and then put the reference at the end.

**Comment by tirthbha** [comment]
> Hy, so while writing documemtation, where are we supposed to place the references? Should we place it at last or should we put it in the the exact place where it is used? @tirthbha any idea?

@poojashresthacode yeah at the end will make more sense and better to cite for those references on the required places.
