### ISSUE TITLE
Who will be the maintainer?

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework2G1#4]
I was maintainer in my first group so I don't think I should be it again.

**Comment by uarif** [comment]
I would like to be the maintainer if its okay with you both @JustinJaniszewski @tirthbha

**Comment by uarif** [comment]
He told me orally, So yes, I will be the maintainer, let's wait for Dr. Tim.  @JustinJaniszewski @tirthbha
