### ISSUE TITLE
Milestone

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework2G1#47]
Other than the maintainer, can we create milestone?

**Comment by uarif** [comment]
> Other than the maintainer, can we create milestone?

I think so.

**Comment by JustinJaniszewski** [comment]
I don't think so, I don't see how.

**Comment by s4il3sh** [comment]
No, you can't.

**Comment by uarif** [comment]
**That is what AI says,** 


Yes, in GitHub, milestone creation is not limited to repository maintainers. Project collaborators, team members, and contributors with the appropriate permissions can create milestones for a repository.

Here's how you can create a milestone in a GitHub repository:

Navigate to the Repository: Go to the GitHub repository where you want to create the milestone.

Click on "Issues": In the repository's menu, click on the "Issues" tab. This will take you to the Issues section of the repository.

Click on "Milestones": In the Issues section, you'll see a tab labeled "Milestones." Click on it to access the milestones for the repository.

Create a New Milestone:

On the milestones page, you'll have an option to "Create a milestone." Click on that button.
Fill in the details for the milestone, including the title, due date (if applicable), and description.
You can also assign the milestone to a specific user or team if needed.
Create the Milestone: After filling in the details, click the "Create milestone" button to create the milestone.

Once the milestone is created, it can be associated with issues and pull requests, helping you track progress and organize work within the repository.

It's worth noting that the ability to create milestones may depend on the repository's settings and the permissions granted to collaborators. If you have the necessary permissions, you should be able to create milestones to help manage project tasks and goals.
