### ISSUE TITLE
Task assignment..

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework2G1#5]
We should also, discuss and assign the task to everyone.

**Comment by JustinJaniszewski** [comment]
I assume we are still assigning in terms of algorithm, documentation, and unit test. I tasked with the unit tests last homework so I think I should try either the algorithm or documentation this time.

**Comment by uarif** [comment]
@JustinJaniszewski I would like to go with the code part, I did documentation last time. Even though, I am not an expert in coding, but I would go with that, If that's fine with @tirthbha

**Comment by tirthbha** [comment]
@uarif @JustinJaniszewski Yeah ! I will go for documentation.

**Comment by JustinJaniszewski** [comment]
Alright then I guess I could do unit test again

**Comment by uarif** [comment]
Okay then, All settled.
