### ISSUE TITLE
Check the Final Documentation

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework2G1#53]
@uarif I have completed my task regarding the documentation and please have a look at that. Needs any changes or else?  @JustinJaniszewski  you can add your unit test result there.

**Comment by JustinJaniszewski** [comment]
Not sure what to add to your documentation. I added tests to the code to make sure it equals the expected value.

**Comment by uarif** [comment]
Okay guys I think we should close this issue
