### ISSUE TITLE
Matrix_multiplication code doesn't stop. 

### ISSUE THREAD

**Issue by JustinJaniszewski** [ubsuny/23-Homework2G1#56]
I'm not sure if i fully understand the file or not. In that file (when I run it on replit.com), it keeps running the plot part. Which meant I was forced to put the unit tests before the plot. I don't believe it is any big deal or will affect the data, etc. However, I just thought I would bring it to your attention and let you decide for yourself.

**Comment by s4il3sh** [comment]
@JustinJaniszewski I checked the code, and it is working perfectly for me.

**Comment by JustinJaniszewski** [comment]
okay nevermind then. It may be an issue on my end.
