### ISSUE TITLE
Final Check!

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework2G1#58]
@uarif @JustinJaniszewski Guys it seems fine from my side regarding the documentation and other stuffs added to our repository. What about you guys?

**Comment by AhmedCode99** [comment]
looks good

**Comment by uarif** [comment]
We are also done, I guess. @tirthbha

**Comment by tirthbha** [comment]
Yeah we are done. @***@***.***>
Only this that we can do now is to add references like papers.
________________________________

**Comment by uarif** [comment]
I dont think if that's necessary
