### ISSUE TITLE
Tasks in this HW..

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework2G1#6]
Well, If I understand it correctly, we will have three main tasks in this HW#2. 
1) Writing code for a matrix operation. (I guess one using Einsum and one with any other? I guess.)
2) Checking the execution time?#
3) Documentation.
If you have anything to share, just enlighten me, please, if that's not what the HW asks. I just read it briefly and got to this point. @tirthbha @JustinJaniszewski

**Comment by reshnashrestha** [comment]
I am also confused about the question.
(1. Is the homework about running matrix operations using different IDE? 
2. Is it about running the operation with various methods including Einstein notation? )
and then comparing the execution time?
1st or 2nd? which one do we need to follow? @laserlab

**Comment by uarif** [comment]
I guess, if I understand it correctly, your point #2, is what the professor wants us to do. But let's confirm from him once.
