### ISSUE TITLE
Einstein notation

### ISSUE THREAD

**Issue by LinxuanHu** [ubsuny/23-Homework2G1#7]
do you know what is Einstein notation

**Comment by uarif** [comment]
> do you know what is Einstein notation

Einstein summation convention, is an easy way to represent and perform operations involving tensors, such as vectors and matrices. You can do it with other methods too, but I guess, it is the easy and more compact method. You can google it for further explanation, notation and how to use it. @LinxuanHu

**Comment by sharmistharanit** [comment]
One example is included in google collab. You can check it from there.

**Comment by AhmedCode99** [comment]
Here is a useful resource:

https://numpy.org/doc/stable/reference/generated/numpy.einsum.html
